env:
  global:
    - JACOCO_SOURCE_PATH=src/main/java
    - CC_TEST_REPORTER_ID=2b849c0fe243827ab0460edd83bb1ee75c2c518c453e59b8f8b54686372ea215
language: java
jdk:
  - oraclejdk11
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter format-coverage build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
